// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 ///import 'firebase_options.dart';
/// // ...
 ///await Firebase.initializeApp(
   ///options: DefaultFirebaseOptions.currentPlatform,
 ///);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjN3BNCbgVvl7fsFDUiZEz9qMsFpRDc_E',
    appId: '1:887040386387:web:4520a6c2c69f77def26da6',
    messagingSenderId: '887040386387',
    projectId: 'gridscout-abb7b',
    authDomain: 'gridscout-abb7b.firebaseapp.com',
    storageBucket: 'gridscout-abb7b.appspot.com',
    measurementId: 'G-W7HDXK7RH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8lIvNN5db0DR18K-k2U6uR-qC5flVSU',
    appId: '1:887040386387:android:7135d1b9f5164e91f26da6',
    messagingSenderId: '887040386387',
    projectId: 'gridscout-abb7b',
    storageBucket: 'gridscout-abb7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYWVsastKp9xOgxUiOsDsC5R03gsOik6E',
    appId: '1:887040386387:ios:2820d464c6bfdbfcf26da6',
    messagingSenderId: '887040386387',
    projectId: 'gridscout-abb7b',
    storageBucket: 'gridscout-abb7b.appspot.com',
    iosBundleId: 'com.example.gridScout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYWVsastKp9xOgxUiOsDsC5R03gsOik6E',
    appId: '1:887040386387:ios:2820d464c6bfdbfcf26da6',
    messagingSenderId: '887040386387',
    projectId: 'gridscout-abb7b',
    storageBucket: 'gridscout-abb7b.appspot.com',
    iosBundleId: 'com.example.gridScout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjN3BNCbgVvl7fsFDUiZEz9qMsFpRDc_E',
    appId: '1:887040386387:web:bdaf81ee2e962baaf26da6',
    messagingSenderId: '887040386387',
    projectId: 'gridscout-abb7b',
    authDomain: 'gridscout-abb7b.firebaseapp.com',
    storageBucket: 'gridscout-abb7b.appspot.com',
    measurementId: 'G-PQNVXGW8XL',
  );
}
